---
data_dir: "../"
# ALTERING THESE REQUIRES REBUILDING THE INDEX!!
model_name: "ViT-B-32"
pretrained: "laion2b_s34b_b79k"
# TODO: move this to a command line arg
index_filepath: "index.ann"
index_to_taxon_filepath: "index_to_taxon_info.pickle"
# TODO: move this to a command line arg
num_trees: 500
prompt_templates:
  - "A photo of a {label}"
  - "A bad photo of a {label}"
  - "A cropped photo of a {label}"
  - "A close up of a {label}"
  - "A blurry photo of a {label}"
